spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metro?createDatabaseIfNotExist=true
    username: root
    password: pass
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 2424