spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/api/auth/**
          uri: http://localhost:2424
          filters:
            - AuthenticationFilter
        - id: account-service
          predicates:
            - Path=/test
          uri: http://localhost:3434
          filters:
            - AuthenticationFilter

server:
  port: 6969